name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: front/package-lock.json
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Build project
        run: |
          cd front
          npm run build

      - name: Build Docker image
        run: docker build -t elvis1971/bobapp-front -f front/Dockerfile front

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN_FRONTEND }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME_FRONT }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push bobapp-front

      - name: Run container
        run: docker run -p 81:81 --name bobapp-front -d bobapp-front
