name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: front/package-lock.json
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Build project
        run: |
          cd front
          npm run build

      - name: Build Docker image
        run: docker build -t elvis1971/bobapp-front -f front/Dockerfile front

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN_FRONTEND }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push elvis1971/bobapp-front

      - name: Stop and remove existing container
        run: |
          docker stop bobapp-front || true
          docker rm bobapp-front || true

      - name: Run container
        run: docker run -p 81:81 --name bobapp-front -d elvis1971/bobapp-front

      - name: Add summary
        run: |
          echo "# Création de secrets : DOCKER_HUB_ACCESS_TOKEN_FRONTEND" >> $GITHUB_STEP_SUMMARY
          echo "Préambule : Se connecter sur son Docker" >> $GITHUB_STEP_SUMMARY
          echo "## https://login.docker.com" >> $GITHUB_STEP_SUMMARY
          echo "Cliquez sur votre nom d'utilisateur en haut à droite et sélectionnez \"Account Settings\"" >> $GITHUB_STEP_SUMMARY
          echo "- Personal access tokens, cliquez sur \"New Access Token\"" >> $GITHUB_STEP_SUMMARY
          echo "- Donnez un nom à votre token (par exemple, \"GitHub Actions Frontend\")" >> $GITHUB_STEP_SUMMARY
          echo "- Choisissez la durée et les permissions et cliquez sur \"Generate\"" >> $GITHUB_STEP_SUMMARY
          echo "- Copiez votre token" >> $GITHUB_STEP_SUMMARY
          echo "Rendez-vous sur GitHub, dans le repository du projet" >> $GITHUB_STEP_SUMMARY
          echo "- Cliquez sur \"Settings\" puis \"Secrets\"" >> $GITHUB_STEP_SUMMARY
          echo "- Cliquez sur \"New repository secret\"" >> $GITHUB_STEP_SUMMARY
          echo "- Nommez votre secret \"DOCKER_HUB_ACCESS_TOKEN_FRONTEND\"" >> $GITHUB_STEP_SUMMARY
          echo "- Collez votre token" >> $GITHUB_STEP_SUMMARY
          echo "- Faites la même chose pour : DOCKER_HUB_USERNAME" >> $GITHUB_STEP_SUMMARY
          echo "- Le nom est celui de votre compte Docker. Cliquez sur l'icône profil en haut à droite pour le voir" >> $GITHUB_STEP_SUMMARY
          
